#!/usr/bin/env python2.7

# Either takes a list of CSV bpm formatted files or a single CSV bpm
# formatted file in stdin and translates 'Y...' yeast gene names to 
# the more recognizable product names.

import csv
import sys

import MySQLdb as mysql

mysql_user = 'yeast3d'
mysql_pass = 'EGqTPuaeMcuMeYb3'

__mapping = { }

__conn = mysql.connect(user=mysql_user, passwd=mysql_pass, db='yeast3d',
                     host='home.burntsushi.net', port=3306)
__cursor = __conn.cursor(mysql.cursors.DictCursor)

__cursor.execute('SELECT product_name, locus_tag FROM gene')
for gene in __cursor.fetchall():
    __mapping[gene['locus_tag'].lower()] = gene['product_name']

def nice_name(locus_tag):
    return __mapping.get(locus_tag.lower(), locus_tag)

def translate_csv(i, o):
    ids = csv.reader(i, delimiter='\t')
    locuses = csv.writer(o, delimiter='\t')

    for row in ids:
        locuses.writerow([row[0]] + map(nice_name, row[1:]))

if len(sys.argv) > 1:
    for f in sys.argv[1:]:
        if f[-3:] != 'csv':
            continue

        i = open(f)
        o = open('nice-%s' % f, 'w+')
        translate_csv(i, o)
else:
    translate_csv(sys.stdin, sys.stdout)

