#!/usr/bin/env python2.7

import csv

from bpm import conf, emap, parallel, partition, prune

if __name__ == '__main__':
    parallel.print_progress()

    emap.load_genes() # Creates global variables emap.genes and emap.gis

    # Calculate the total number of steps so we can measure progress
    parallel.steps = conf.M + emap.genecount() + sum(parallel.costs.values())

    bpms = partition.bpms()
    bpms = prune.prune(bpms)
    
    outf = open(conf.bpm, 'w+')
    out = csv.writer(outf, delimiter='\t')
    for i, (mod1, mod2) in enumerate(bpms):
        mod1, mod2 = list(mod1), list(mod2)
        out.writerow(['BPM%d/Module1' % i] + mod1)
        out.writerow(['BPM%d/Module2' % i] + mod2)

