#!/usr/bin/env python2

import argparse
import csv

parser = argparse.ArgumentParser(
    description='Extract yeast genes from the output of ortholog-inparanoid.',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
aa = parser.add_argument
aa('yeastorthologs', type=str,
   metavar='INPUT_YEAST_ORTHOLOGS_LIST_FILE',
   help='Location of the orthologous yeast genes output file.')
aa('yeastgenes', type=str,
   metavar='OUTPUT_YEAST_GENES',
   help='Location of the othologous yeast gene list file.')
conf = parser.parse_args()

out = open(conf.yeastgenes, 'w+')

reader = csv.reader(open(conf.yeastorthologs))
for row in reader:
    species = row[2]
    if not species.startswith('Saccharomyces cerevisiae'):
        continue
    gene = row[4]
    if not gene.startswith('Y'):
        continue
    print >> out, gene.strip()

