#!/usr/bin/env python2

import argparse
import csv
import sys

parser = argparse.ArgumentParser(
    description='Compare a list of yeast genes to a GI data set.',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
aa = parser.add_argument
aa('gi', type=str,
   metavar='INPUT_GENETIC_INTERACTION_FILE',
   help='Genetic interaction (gi) data file.')
aa('yeastgenes', type=str,
   metavar='INPUT_YEAST_GENES',
   help='Location of the othologous yeast gene list file.')
conf = parser.parse_args()

out = sys.stdout
gigenes, cmpgenes = set(), set()

reader = csv.reader(open(conf.gi), delimiter='\t')
for row in reader:
    g1, g2 = row[0], row[1]
    gigenes.add(g1.upper())
    gigenes.add(g2.upper())

for gene in open(conf.yeastgenes):
    cmpgenes.add(gene.strip().upper())

common = gigenes.intersection(cmpgenes)
diff = cmpgenes.difference(gigenes)

print >> out, 'Genes in common (%d):' % len(common)
print >> out, '%s' % ', '.join(sorted(common))

print

print >> out, 'Genes in %s but not in GI (%d):' % (conf.yeastgenes, len(diff))
print >> out, '%s' % ', '.join(sorted(diff))

