#!/bin/sh

if [ $# != 1 ]; then
  echo "Usage: $(basename $0) test-name" >&2
  exit 1
fi

test_name=$1

cd $BPM/output

$BPM/tests/run-mkbpms $test_name /data/chrombio.csv /data/essentials \
  '0.9' '250' '0.66' 3
# $BPM/tests/run-mkbpms $test_name /data/chrombio.csv /data/essentials \ 
  # '0.9' '500' '0.10' 2 

# This stuff runs *a lot* faster on my local desktop
scp ${test_name}_*.bpm Ocelot:~/data/graduate/research/bpm/output/
ssh Ocelot "~/data/graduate/research/bpm/tests/run-go-from-pulsar $test_name"

# $BPM/tests/run-go-and-analyze '0.01' \ 
  # /data/chrombio.csv /data/essentials ${test_name}_*.bpm \ 
  # > $BPM/output/$test_name-results.csv 

