#!/bin/sh

if [ $# != 1 ]; then
  echo "Usage: $(basename $0) test-name" >&2
  exit 1
fi

test_name=$1

source ~/.envrc

cd $BPM/output

$BPM/tests/run-go-and-analyze '0.01' \
  /tmp/chrombio.csv /tmp/essentials ${test_name}_*.bpm \
  > $BPM/output/${test_name}-results.csv

