#!/usr/bin/env python2.7

# Either takes a list of CSV bpm formatted files or a single CSV bpm
# formatted file in stdin and translates 'Y...' yeast gene names to 
# the more recognizable product names.

import csv
import sys

import geneids

def translate_csv(i, o):
    ids = csv.reader(i, delimiter='\t')
    locuses = csv.writer(o, delimiter='\t')

    for row in ids:
        locuses.writerow([row[0]] + map(geneids.locus_to_product, row[1:]))

if len(sys.argv) > 1:
    for f in sys.argv[1:]:
        if f[-3:] != 'csv':
            continue

        i = open(f)
        o = open('nice-%s' % f, 'w+')
        translate_csv(i, o)
else:
    translate_csv(sys.stdin, sys.stdout)

