#!/usr/bin/env python2.7

import argparse
import csv

import geneids

parser = argparse.ArgumentParser(
    description='Translate a BPM file with systematic yeast gene names to '
                'standard yeast gene names.',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
aa = parser.add_argument
aa('bpm', type=str,
   metavar='INPUT_BPM_FILE',
   help='BPM file to translate.')
aa('obpm', type=str,
   metavar='OUTPUT_BPM_FILE',
   help='The name of the file to write the input BPM file with the gene names '
        'translated.')
conf = parser.parse_args()

def translate_csv(i, o):
    ids = csv.reader(i, delimiter='\t')
    locuses = csv.writer(o, delimiter='\t')

    for row in ids:
        locuses.writerow([row[0]] + map(geneids.locus_to_product, row[1:]))

translate_csv(open(conf.bpm), open(conf.obpm, 'w+'))

