#!/usr/bin/env python2

import argparse
import itertools

from bpm import bpmreader, geneinter

import geneids

parser = argparse.ArgumentParser(
    description='Print genetic interaction scores for all gene pairs in a BPM.',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
aa = parser.add_argument
aa('geneinter', type=str,
   metavar='INPUT_GENETIC_INTERACTION_FILE', help='Location of the GI file.')
aa('bpm', type=str, metavar='INPUT_BPM_FILE', help='BPM file to translate.')
aa('bpmi', type=int, metavar='BPM_NUMBER', help='The BPM index to use.')
aa('-e', '--essential-list', dest='essentials', type=str, default=None,
   metavar='ESSENTIAL_FILE',
   help='The location of an essential gene list file. (One gene per line.) '
        'Any genes in this file will be excluded from the set of genes used '
        'to generate BPMs.')
aa('-w', '--within', action='store_true')
conf = parser.parse_args()

geneinter.load_genes(conf.geneinter, conf.essentials)

# Read the BPMs
bpms = bpmreader.read(conf.bpm)

if not conf.within:
    # Print the interaction scores between modules.
    for g1 in bpms[conf.bpmi][0]:
        for g2 in bpms[conf.bpmi][1]:
            gi = geneinter.gi(g1, g2)
            print geneids.locus_to_product(g1), geneids.locus_to_product(g2), gi
else:
    # Print the interaction scores within each module
    print 'Module0'
    for g1, g2 in itertools.combinations(bpms[conf.bpmi][0], 2):
        gi = geneinter.gi(g1, g2)
        print geneids.locus_to_product(g1), geneids.locus_to_product(g2), gi
    print '-' * 45
    print 'Module1'
    for g1, g2 in itertools.combinations(bpms[conf.bpmi][1], 2):
        gi = geneinter.gi(g1, g2)
        print geneids.locus_to_product(g1), geneids.locus_to_product(g2), gi

